#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VIId VIII IX X

bspc config window_gap          18

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

$HOME/.config/polybar/launch.sh
picom -fb
nitrogen --restore &
bspc config focused_border_width 0
bspc config mark-ovredir-focused = false
bspc config border_width 2
bspc config border_radius 11
bspc config focused_border_color "#cdd6f4"
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc config -w focused border_width 0
